# Generated by Django 4.1.2 on 2022-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visible_area',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
